### ISSUE TITLE
How to build this project on a local machine?

### ISSUE THREAD

**Issue by chankeypathak** [areebbeigh/codeinterview-backend#1]
Could you share the steps on how to build it locally? e.g. what are the dependencies, how to setup the environment, how to start the daemon etc.

**Comment by areebbeigh** [comment]
Hi. You can install the dependencies by doing `pip install -r requirements.txt`. The current settings.py file has an `InMemoryChannelLayer` for Django channels. While this is fine for working only on the UI, you'll need to set up a RedisChannelLayer/AMQP Channel Layer for the code output logs to be saved to the database.

The front-end and worker sandbox repositories have been linked in the readme :)

**Comment by chankeypathak** [comment]
@areebbeigh Thanks, I'll try that out. Also how to build the front-end?

**Comment by areebbeigh** [comment]
`npm start` to run the development server and `npm run build` to build the dist.
